### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by kostajh** [lepisma/emacs-speech-input#2]
Hi, could you please clarify which versions of Python are supported? On Python 3.9.2 I see:

```
❯ dg.py
Traceback (most recent call last):
  File "/Users/kostajh/src/emacs-speech-input/dg.py", line 5, in <module>
    from deepgram import (DeepgramClient, LiveOptions, LiveTranscriptionEvents,
  File "/Users/kostajh/.local/lib/python3.9/site-packages/deepgram/__init__.py", line 25, in <module>
    from .client import Deepgram, DeepgramClient
  File "/Users/kostajh/.local/lib/python3.9/site-packages/deepgram/client.py", line 403
    match self._parent:
          ^
SyntaxError: invalid syntax
```

**Comment by kostajh** [comment]
Oh, it should be Python 3.10 and above.

**Comment by lepisma** [comment]
Thanks!
